theme: jekyll-theme-hacker
title: "Snippet Vault"
description: "Where Code Comes to Chill Before It’s Useful Again"

github:
  url: https://github.com/nevalsingh
  repository_url: https://github.com/nevalsingh

header_pages:
  - index.md
  - about.md
  - blog.md
