theme: jekyll-theme-hacker
title: "Snippet Vault"
description: "Where Code Comes to Chill Before It’s Useful Again"
github:
  is_project_page: false
header_pages:
  - index.md
  - about.md
  - blog.md
